#!/bin/bash

################################################################################################
# POP-C++ Release Archiver
# Author : Clement Valentin (clementval)
# Creation date : 06/04/2011
# Description : This script is used to create a releasable archive of POP-C++ 
# ----------------------------------------------------------------------------------------------
# IMPORTANT : Please, keep this log up to date 
#
# Update log
# Date         Author      Description
# 31/03/2011	clementval	First version of this script
# 05/06/2012	clementval	Update script to have proper release without any dev folder or files
################################################################################################


################################################################
# Define the function to print the program usage
################################################################
usage()
{
cat << EOF

POP-C++ releaser script v1.0

This program is used to create a releasable archive of POP-C++

Usage: create_release <version>
       - version should be in the form of 1.0, 2.0, 2.5.1 ...
EOF
}



if [ "x$1" == "x" ]
then
   echo "[ERROR] You must specify a version number"
   usage
   exit
fi

echo "IMPORTANT FOR THE RELEASE"
echo "Did you update the following files:"
echo "- ChangeLog"
echo "- RELEASE_NOTES"
echo "Did you increment the version number in the configure.ac file ?"
echo "Did you regenerate the files with autoreconf ?"
echo "If everything is fine just proceed with the archive ! (y/n)"


#Clean the current version of POP-C++
make clean 


VERSION=$1
#Date of the arhiving
DDATE=$(date +%Y%m%d)
RELDIR="popcpp_"$VERSION"_build_"$DDATE
ARCHIVE="$RELDIR.tar"
IGNORED=" dev virtualtest autom4te.cache .svn"



mkdir $RELDIR
GOODDIR=$(ls . | grep -v ReleaseNotes.dev.txt | grep -v documentation | grep -v virtualtest | grep -v autom4te.cache | grep -v stamp-h1 | grep -v create_release | grep -v ChangeLog | grep -v config.log | grep -v config.status)

echo $GOODDIR

for d in $GOODDIR
do
	if [ "x$d" != "x$RELDIR" ]
	then
		cp -R $d $RELDIR
		echo "cp -R $d $RELDIR"
	fi
done


tar -cf $ARCHIVE --exclude='.svn' $RELDIR/*
gzip $ARCHIVE
rm -rf $RELDIR

