#!/bin/bash

#############################################################################################
# POP-C++ Archive Releaser
# Author : Clement Valentin (clementval)
# Creation date : 06/04/2011
# Description : This script is used to create a releasable archive of POP-C++ version 
# -------------------------------------------------------------------------------------------
# IMPORTANT : Please, keep this log up to date 
#
# Update log
# Date         Author      Description
# 31/03/2011	clementval	First version of this script
#############################################################################################


################################################################
# Define the function to print the program usage
################################################################
usage()
{
cat << EOF

POP-C++ releaser script v1.0

This program is used to create a releasable archive of POP-C++

Usage: create_release <version>
       - version should be in the form of 1.0, 2.0, 2.5.1 ...
EOF
}



if [ "x$1" == "x" ]
then
   echo "[ERROR] You must specify a version number"
   usage
   exit
fi

make clean 


VERSION=$1
DDATE=$(date +%Y%m%d)
RELDIR="popcpp_"$VERSION"_build_"$DDATE
ARCHIVE="$RELDIR.tar"

echo "The archive $RELDIR.tar.gz will be created"

mkdir $RELDIR

FILES=$(find ./ -not \( -name .svn -a -prune \))

for FILE in $FILES
do
   NEWPATH=$(echo ${FILE:1})
   #cp $FILE $RELDIR$NEWPATH
   if [ -d $FILE ]
   then
      if [ "$FILE" != "./" ]
      then
         #echo "mkdir $RELDIR$NEWPATH"
         mkdir $RELDIR$NEWPATH
      fi
   else
      #echo "cp $FILE $RELDIR$NEWPATH"
      if [ "$FILE" != "./create_release" ]
      then
         cp $FILE $RELDIR$NEWPATH
      fi
   fi
done

tar -cvf $ARCHIVE $RELDIR/*
gzip $ARCHIVE

rm -rf $RELDIR
