#include "popc_group_broker.h"
#include "pop_xmp_object_object.h"

// Generated by the compiler
class POPXMPObject_popcobject_Broker : virtual public POPC_GroupBroker
{
public:
  POPXMPObject_popcobject_Broker();
  virtual bool Invoke(unsigned method[3],  paroc_buffer &__brokerbuf, paroc_connection *peer);
protected:
  void Invoke_POPXMPObject_10(paroc_buffer &__paroc_buf, paroc_connection *__interface_output);
  void Invoke_execute_xmp_1_12(paroc_buffer &__paroc_buf, paroc_connection *__interface_output);
  void Invoke_set_value_13(paroc_buffer &__paroc_buf, paroc_connection *__interface_output);
public:
  static POPC_GroupBroker *_init();
  //static paroc_broker_factory _fact;
};