#include "paroc_interface.h"

class POPXMPObject : public paroc_interface {
public:
  POPXMPObject();
  // Must be generated by the compiler
  POPXMPObject(const paroc_accesspoint &p) { od.executable("./pop_xmp_object.obj"); Bind(p); }; 
  ~POPXMPObject();


  // Must be generated by the compiler
  virtual const char* ClassName() { return "POPXMPObject"; }

};
