#line 2 "parser.yy.cc"

#line 4 "parser.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[309] =
    {   0,
        0,    0,   65,   63,    1,   14,   62,   62,   62,   62,
       62,   63,   63,   51,   62,   63,   62,   63,   63,   62,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   62,    9,   62,    1,   58,    0,
       10,    0,   55,    0,   11,    0,   52,    0,   53,    0,
       51,   36,   60,   57,   59,    0,   61,    0,    0,    0,
       50,    0,   50,   50,   50,   50,   50,   50,   30,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   56,    9,    9,    9,    9,    0,    0,
       10,    0,   11,    0,    0,    0,    0,   53,    0,    0,

       50,   50,   50,   50,   50,   50,   50,   31,   50,   50,
       50,   50,   50,   33,   50,   50,   50,   50,   50,   50,
       50,   50,    9,    7,    9,    0,   52,   54,    0,    0,
       13,    0,   50,   50,   20,   50,   32,   50,   17,   50,
       50,   50,   38,   50,   50,   50,   50,   39,   50,   28,
       40,   50,   50,   50,    9,    9,    0,    2,   13,    0,
        0,   12,   50,   29,   16,   26,   35,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,    9,    0,    8,
        9,    0,    0,   12,   50,   50,    0,   34,   50,   50,
       50,   22,   50,   50,   27,   50,   50,   50,    8,    8,

        9,    0,    0,   50,   50,   50,   23,   50,   50,    0,
       50,   49,   50,   25,    8,    9,    0,   37,   19,   15,
       50,   21,    0,    0,    0,    0,   50,   50,    9,    9,
        9,    9,    0,   24,    0,    0,    0,    0,   18,    0,
        9,    9,    9,    0,    0,   42,    0,    0,    0,    0,
        0,    0,    9,    9,    9,    0,   45,   44,    0,    0,
        0,    0,    0,    9,    9,    9,    0,   47,    0,   41,
        0,    0,    9,    9,    9,    0,   46,   43,    0,    9,
        9,    9,    0,    3,   48,    9,    9,    9,    9,    9,
        3,    9,    5,    9,    9,    6,    5,    5,    9,    6,

        6,    9,    9,    9,    4,    4,    4,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    4,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   29,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   28,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    2,    2,    3,    1,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    6,
        7,    1,    1,    1,    1,    1,    1,    8,    8,    1,
        1,    1,    1,    8,    1,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1,    9
    } ;

static yyconst flex_int16_t yy_base[325] =
    {   0,
        0,   58,  776, 1283,   64, 1283,  751,   62, 1283,  763,
       58,  752,   56,   53,  750,  746,  745,  744,   74,   77,
       80,   84,   88,   96,  100,  104,  108,  111,  120,   80,
       95,  102,  116,  124,  705,  127,  179,   94, 1283,   88,
     1283,  128, 1283,  126, 1283,  155,  150,  752,    0,  745,
       54, 1283, 1283, 1283, 1283,  185, 1283,  189,  728,  192,
      148,  742,  162,  161,  166,  171,  176,  175,  180,  190,
      198,  199,  206,  211,  221,  213,  234,  205,  232,  236,
      242,  243,  247, 1283,    0,  281,  301,  709,  235,  725,
      168,  169,  192,  260,  740,  745,  734,    0,  714,  304,

      266,  275,  273,  279,  289,  298,  300,  294,  319,  305,
      327,  313,  323,  328,  337,  338,  349,  351,  356,  360,
      362,  367,  310, 1283,  714,  222,  728, 1283,  700,  335,
      724,  206,  372,  381,  385,  390,  394,  396,  400,  404,
      412,  418,  419,  427,  425,  434,  446,  440,  441,  448,
      453,  459,  469,  464,  314,  700,  687, 1283,  711,  708,
      524,    0,  477,  478,  482,  483,  538,  493,  501,  507,
      512,  511,  516,  522,  534,  535,  526,  391,  715,    0,
      672,  677,  590,    0,  545,  553,  600, 1283,  559,  571,
      564,  569,  578,  626,  580,  596,  602,  603,    0,    0,

      673,  663,  641,  604,  612,  610,  626,  631,  633,  670,
      639,  640,  641,  645,    0,  675,  655,  647,  654,  670,
      677,  675,  645,  636,  620,  598,  682,  737,  699,  582,
      577,  586,  563,  691,  572,  541,  537,  533,  698,  753,
      530,  521,  528,  521,  498, 1283,  479,  457,  465,  458,
      442,  448,  427,  418,  402,  436, 1283, 1283,  378,  395,
      374,  352,  338,  337,  318,  332,  421, 1283,  299, 1283,
      306,  291,  264,  271,  227,  267, 1283, 1283,  189,  411,
      149,  442,  165,    0, 1283,  461,  805,  125,  500,  863,
        0,    0,  921,  122,    0,  979,  137,    0,  520,  124,

        0,  529, 1037,    0, 1095,  123,    0, 1283, 1155, 1164,
     1172, 1180, 1189, 1198, 1206, 1210, 1217, 1225, 1229, 1237,
     1246, 1255, 1264, 1273
    } ;

static yyconst flex_int16_t yy_def[325] =
    {   0,
      308,    1,  308,  308,  308,  308,  308,  309,  308,  308,
      310,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      311,  311,  311,  311,  311,  311,  311,  311,  311,   29,
       29,   29,   29,   29,  308,  312,  308,  308,  308,  309,
      308,  309,  308,  310,  308,  310,  308,  313,  314,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
       29,  308,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,  308,  312,  312,  312,  312,  308,  308,
      309,  309,  310,  310,  308,  313,  308,  314,  308,  315,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,  312,  308,  312,  308,  308,  308,  308,  315,
      316,  317,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,  318,  312,  308,  308,  316,  308,
      317,  319,   29,   29,   29,   29,  311,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,  318,  320,  321,
      312,  308,  315,  319,   29,   29,  308,  308,   29,   29,
       29,   29,   29,  311,   29,   29,   29,   29,  322,  321,

      312,  308,  315,   29,   29,   29,   29,   29,   29,  308,
       29,   29,   29,   29,  322,  312,  308,   29,   29,   29,
       29,   29,  308,  308,  308,  308,   29,  311,  312,  312,
      312,  312,  308,   29,  308,  308,  308,  308,   29,  308,
      312,  312,  312,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  312,  312,  312,  308,  308,  308,  308,  308,
      308,  308,  308,  312,  312,  312,  308,  308,  308,  308,
      308,  308,  312,  312,  312,  323,  308,  308,  308,  312,
      312,  312,  323,  324,  308,  312,  312,  312,  312,  312,
      324,  287,  287,  312,  290,  290,  312,  293,  312,  312,

      296,  312,  312,  303,  303,  312,  305,    0,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308
    } ;

static yyconst flex_int16_t yy_nxt[1348] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,    9,    9,   10,
       11,    9,    9,    9,    9,    9,    9,   12,   13,   14,
       15,    9,   16,   17,   18,   19,   20,   21,   21,    9,
        4,    9,    9,   22,    9,   23,   21,   24,   21,   25,
       21,   21,   21,   26,   21,   21,   21,   27,   21,   28,
       29,   21,   30,   31,   32,   33,   34,   21,   21,   21,
        9,   35,    9,    9,   36,   38,   38,   41,   45,   48,
       50,   50,   51,   51,   49,   56,   56,   56,   58,   58,
       58,   60,   60,   60,   37,   60,   60,   60,   46,   60,
       60,   60,   42,   41,   57,   38,   38,   60,   60,   60,

       62,   60,   60,   60,   62,   60,   60,   60,   62,   60,
       60,   60,   60,   60,   60,   61,   62,   63,   42,   75,
       62,   60,   60,   60,   62,  306,  300,   59,   62,   86,
       61,   62,   61,   91,   76,   61,   45,   61,   77,  297,
       62,   64,   66,   65,   80,   67,   87,   61,   68,   78,
       61,   61,   69,   79,   61,   72,   46,   61,   92,   61,
       81,  299,  294,   70,   82,   93,   71,   83,   61,   47,
      284,   61,   73,   41,   91,   74,   61,   88,   95,   61,
       89,   89,   89,   61,  288,   94,   56,   56,   56,   95,
       58,   58,   58,   60,   60,   60,   61,   61,   42,   92,

       61,   61,   45,   61,  101,   57,  104,  161,  161,  161,
       61,   61,   62,   61,   61,   61,   61,   61,   61,  102,
      103,   61,   46,   61,  105,   61,   61,   61,   61,   90,
      106,   61,   61,   61,   61,   61,   89,   89,   89,   59,
       61,   61,   61,  285,  107,   61,   61,  112,   61,  110,
       61,  109,  108,   61,   61,  111,   61,  117,   61,  129,
       61,   61,  113,   61,  114,   61,   61,   61,   61,   61,
       93,   61,  284,   61,  157,  115,   61,   61,   61,  119,
      118,  282,   61,   86,   61,   90,   61,   61,   61,   61,
       94,   61,  120,  116,   61,   61,  121,   61,   61,  122,

       87,   61,   61,  123,  124,  130,  130,  130,   61,  133,
       61,  281,  123,  124,   61,  155,  280,  179,   61,  180,
       87,   61,  135,  134,   61,   61,  137,   61,   61,   61,
       61,   61,  136,   61,   61,   61,  130,  130,  130,  140,
       61,   61,  138,  279,   61,  139,   61,  278,   61,   61,
       61,  277,   61,   61,   61,   61,  141,   61,   61,  145,
       61,  142,   61,   61,  143,   61,  146,  132,   61,  275,
      274,   61,   61,   61,   61,   61,  273,  148,   61,   61,
       61,  144,   61,   61,   61,  147,   61,  272,  150,   61,
       61,   61,   61,   61,  179,   61,  180,   61,  132,  152,

      271,   61,   61,   61,  149,  153,   61,   61,   61,  151,
      163,   61,   61,  286,   61,   61,   61,   61,  164,   61,
       61,  154,   61,  267,   61,   61,  276,   61,  270,   61,
      269,   61,  268,   61,  287,   61,   61,   61,  267,   61,
       61,  266,   61,  165,  289,   61,   61,   61,   61,   61,
      166,   61,   61,  169,   61,   61,   61,  265,  168,   61,
       61,  167,   61,  286,   61,  290,  170,   61,  171,   61,
       61,   61,  264,   61,   61,   61,   61,   61,  174,   61,
       61,   61,   61,   61,  287,  173,   61,  172,   61,   61,
      263,  262,   61,   61,   61,   61,   61,  175,   61,   61,

       61,   61,  289,   61,   61,   61,  261,  260,   61,  259,
      176,   61,   61,   61,   61,  185,   61,   61,   61,  177,
      258,   61,  302,  290,   61,  161,  161,  161,  189,   61,
       61,  302,   61,   61,   61,   61,   61,  186,   61,  187,
      187,  187,   61,  303,  191,   61,   61,   61,   61,  192,
      257,   61,  303,   61,  194,  190,   61,   61,   62,   61,
      256,  198,   61,   61,   61,  193,   61,   61,   61,   61,
       61,   61,  255,  196,   61,  254,  195,   61,   61,  253,
       61,   61,  248,  197,  204,  247,   61,   61,   61,   61,
       61,  203,  203,  203,   61,  246,  205,   61,  188,   61,

       61,  187,  187,  187,   61,   61,   61,  245,   61,  244,
      207,   61,  206,   61,   61,   61,   61,  209,  208,   61,
       62,   61,  243,   61,   61,  242,   61,  210,  210,  210,
       61,   61,   61,   61,  241,  211,  212,   61,   61,   61,
      238,  213,  203,  203,  203,   61,   62,   61,   61,  214,
      219,   61,  218,  308,   61,   61,   61,   61,   61,   61,
      188,   61,   61,  220,   61,   61,   61,   61,   61,  237,
      221,  210,  210,  210,   61,   61,   61,  229,   61,  228,
       61,   61,   61,   61,  236,  222,   61,  235,   61,   61,
       62,  227,   61,   61,   61,   61,   61,   61,  233,   61,

       61,  229,   61,  217,  308,   61,   61,  223,  216,   61,
       61,  230,   61,  224,  202,  234,  225,   61,  231,  201,
      199,  239,   61,  226,  232,   61,   61,   61,  183,   61,
       61,  160,   61,   61,   61,  230,  182,   61,  240,  240,
      240,  181,  231,   61,  160,  158,   61,  127,  232,  156,
       61,  129,  128,   61,  240,  240,  240,   62,   97,  127,
      126,  125,  100,   99,   47,   97,   84,   55,   54,   53,
       52,   47,   43,   62,   39,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      249,  308,  308,  308,  308,  308,  250,  308,  308,  251,

      308,  308,  308,  308,  308,  308,  252,  292,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  293,  293,  308,  308,  308,  308,  293,  308,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  295,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      296,  296,  308,  308,  308,  308,  296,  308,  296,  296,

      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  297,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      298,  308,  308,  308,  308,  308,  308,  308,  298,  298,
      308,  308,  308,  308,  298,  308,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  300,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  301,  308,

      308,  308,  308,  308,  308,  308,  301,  301,  308,  308,
      308,  308,  301,  308,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  304,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  305,  305,  308,  308,  308,  308,
      305,  308,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  306,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  307,  308,  308,  308,  308,  308,
      308,  308,  307,  307,  308,  308,  308,  308,  307,  308,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   44,   44,   44,  308,   44,   44,
       44,   44,   44,   61,   61,  308,  308,   61,   61,   61,
       85,   85,  308,   85,   85,   85,   85,   85,   85,   96,
       96,   96,  308,  308,   96,   96,   96,   96,   98,   98,

      308,   98,   98,   98,   98,   98,   98,  131,  131,  308,
      308,  308,  308,  131,  131,  159,  159,  159,  162,  162,
      308,  308,  308,  308,  162,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  184,  308,  184,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  200,  200,  308,  200,
      200,  200,  200,  200,  200,  215,  215,  308,  215,  215,
      215,  215,  215,  215,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  291,  291,  308,  291,  291,  291,  291,
      291,  291,    3,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308
    } ;

static yyconst flex_int16_t yy_chk[1348] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    5,    5,    8,   11,   13,
       14,   51,   14,   51,   13,   19,   19,   19,   20,   20,
       20,   21,   21,   21,    2,   22,   22,   22,   11,   23,
       23,   23,    8,   40,   19,   38,   38,   24,   24,   24,

       21,   25,   25,   25,   22,   26,   26,   26,   23,   27,
       27,   27,   28,   28,   28,   30,   24,   22,   40,   30,
       25,   29,   29,   29,   26,  306,  300,   20,   27,   36,
       31,   28,   30,   42,   31,   30,   44,   32,   31,  297,
       29,   23,   24,   23,   32,   24,   36,   31,   25,   31,
       31,   33,   26,   31,   32,   29,   44,   32,   42,   34,
       32,  294,  288,   27,   33,   46,   28,   34,   33,   47,
      283,   33,   29,   91,   92,   29,   34,   36,   47,   34,
       37,   37,   37,   61,  281,   46,   56,   56,   56,   47,
       58,   58,   58,   60,   60,   60,   64,   63,   91,   92,

       61,   65,   93,   61,   63,   56,   66,  132,  132,  132,
       68,   67,   60,   64,   63,   69,   64,   63,   65,   64,
       65,   65,   93,   66,   67,   70,   66,   68,   67,   37,
       68,   67,   69,   71,   72,   69,   89,   89,   89,   58,
       78,   73,   70,  279,   70,   70,   74,   74,   76,   73,
       71,   72,   71,   71,   72,   73,   75,   78,   73,  126,
       78,   73,   75,   74,   76,   76,   74,   79,   76,   77,
       94,   80,  276,   75,  126,   77,   75,   81,   82,   80,
       79,  275,   83,   86,   79,   89,   77,   79,   80,   77,
       94,   80,   81,   77,   81,   82,   82,   81,   82,   83,

       86,  101,   83,   87,   87,  100,  100,  100,  103,  101,
      102,  274,  123,  123,  104,  123,  273,  155,  101,  155,
       87,  101,  103,  102,  105,  103,  105,  102,  103,  108,
      102,  104,  104,  106,  104,  107,  130,  130,  130,  107,
      110,  105,  105,  272,  105,  106,  108,  271,  112,  108,
      106,  269,  107,  106,  109,  107,  109,  110,  113,  112,
      110,  110,  111,  114,  111,  112,  113,  100,  112,  266,
      265,  109,  115,  116,  109,  113,  264,  116,  113,  111,
      114,  111,  111,  114,  117,  115,  118,  263,  118,  115,
      116,  119,  115,  116,  178,  120,  178,  121,  130,  120,

      262,  117,  122,  118,  117,  121,  118,  133,  119,  119,
      133,  119,  120,  280,  121,  120,  134,  121,  134,  122,
      135,  122,  122,  267,  133,  136,  267,  133,  261,  137,
      260,  138,  259,  134,  280,  139,  134,  135,  256,  140,
      135,  255,  136,  136,  282,  136,  137,  141,  138,  137,
      138,  138,  139,  142,  143,  139,  140,  254,  141,  140,
      145,  140,  144,  286,  141,  282,  144,  141,  145,  146,
      142,  143,  253,  142,  143,  148,  149,  145,  149,  144,
      145,  147,  144,  150,  286,  147,  146,  146,  151,  146,
      252,  251,  148,  149,  152,  148,  149,  152,  147,  154,

      150,  147,  289,  150,  153,  151,  250,  249,  151,  248,
      153,  152,  163,  164,  152,  163,  154,  165,  166,  154,
      247,  153,  299,  289,  153,  161,  161,  161,  168,  163,
      164,  302,  163,  164,  165,  166,  169,  165,  166,  167,
      167,  167,  170,  299,  170,  168,  172,  171,  168,  171,
      245,  173,  302,  169,  173,  169,  169,  174,  167,  170,
      244,  177,  170,  172,  171,  172,  172,  171,  173,  175,
      176,  173,  243,  175,  174,  242,  174,  174,  177,  241,
      185,  177,  238,  176,  185,  237,  175,  176,  186,  175,
      176,  183,  183,  183,  189,  236,  186,  185,  167,  191,

      185,  187,  187,  187,  192,  186,  190,  235,  186,  233,
      190,  189,  189,  193,  189,  195,  191,  193,  191,  191,
      187,  192,  232,  190,  192,  231,  190,  194,  194,  194,
      193,  196,  195,  193,  230,  195,  196,  197,  198,  204,
      226,  197,  203,  203,  203,  206,  194,  205,  196,  198,
      205,  196,  204,  183,  197,  198,  204,  197,  198,  204,
      187,  207,  206,  206,  205,  206,  208,  205,  209,  225,
      208,  210,  210,  210,  211,  212,  213,  216,  207,  213,
      214,  207,  218,  208,  224,  209,  208,  223,  209,  219,
      210,  211,  212,  213,  211,  212,  213,  214,  217,  218,

      214,  229,  218,  202,  203,  220,  219,  210,  201,  219,
      222,  216,  221,  210,  182,  221,  210,  227,  216,  181,
      179,  227,  220,  210,  216,  220,  234,  222,  160,  221,
      222,  159,  221,  239,  227,  229,  157,  227,  228,  228,
      228,  156,  229,  234,  131,  129,  234,  127,  229,  125,
      239,   99,   97,  239,  240,  240,  240,  228,   96,   95,
       90,   88,   62,   59,   50,   48,   35,   18,   17,   16,
       15,   12,   10,  240,    7,    3,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      240,    0,    0,    0,    0,    0,  240,    0,    0,  240,

        0,    0,    0,    0,    0,    0,  240,  287,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  287,  287,    0,    0,    0,    0,  287,    0,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  290,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      290,  290,    0,    0,    0,    0,  290,    0,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  293,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      293,    0,    0,    0,    0,    0,    0,    0,  293,  293,
        0,    0,    0,    0,  293,    0,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  296,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  296,    0,

        0,    0,    0,    0,    0,    0,  296,  296,    0,    0,
        0,    0,  296,    0,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  303,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  303,  303,    0,    0,    0,    0,
      303,    0,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  305,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  305,    0,    0,    0,    0,    0,
        0,    0,  305,  305,    0,    0,    0,    0,  305,    0,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  310,  310,  310,    0,  310,  310,
      310,  310,  310,  311,  311,    0,    0,  311,  311,  311,
      312,  312,    0,  312,  312,  312,  312,  312,  312,  313,
      313,  313,    0,    0,  313,  313,  313,  313,  314,  314,

        0,  314,  314,  314,  314,  314,  314,  315,  315,    0,
        0,    0,    0,  315,  315,  316,  316,  316,  317,  317,
        0,    0,    0,    0,  317,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  319,    0,  319,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  321,  321,    0,  321,
      321,  321,  321,  321,  321,  322,  322,    0,  322,  322,
      322,  322,  322,  322,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  324,  324,    0,  324,  324,  324,  324,
      324,  324,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser.lex"
#line 2 "parser.lex"

#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <ctype.h>
#include "parser.tab.h"
#include "parser.h"
#include "paroc_utils.h"
#include "debug.h"

  int c;
  int linenumber=0;
  char filename[1024];
  char classname[1024];
  int mutexCount=0;
  int dummyCount=0;

  extern CArrayCharPtr searchpath, sources;
  extern CodeFile *thisCodeFile;

  CArrayChar othercodes(0,32536);
  bool insideClass;
  int startPos=-1;

  /*
#if !defined (YYSTYPE)
#define YYSTYPE long
#endif
  */

  extern YYSTYPE yylval;
  extern char token[];
  extern int yylex(void);

  char tokenbuf[32000];
  char *tokenpos;

  int  PutToken(char *str);
  int PutToken(char chr);
  char *GetToken(int yyval);
  int CountLine(char *str);
  bool IsSystemHeader(char *fname);

  int ReadUntil(char *sep, char *output, int sz);
   
#line 899 "parser.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 59 "parser.lex"


#line 1087 "parser.yy.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 309 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1283 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 61 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
};
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 65 "parser.lex"
{
  startPos=othercodes.GetSize();
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PACK_KEYWORD;
};
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 71 "parser.lex"
{
  char *t1, *t2;
  t1=strchr(yytext,'"');
  if (t1!=NULL)
    {
      t1++;
      t2=strrchr(t1,'"');
      if (t2!=NULL)
	{
	  *t2=0;
	  strcpy(filename,t1);
	  thisCodeFile->SetFileName(filename); 
	  *t2='"';
	}
    }
  //  printf("LINE DIRECTIVE:line:%d in %s\n", linenumber,filename);
};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 89 "parser.lex"
{
  char *t=strchr(yytext,'=');
  t++;
  while (isspace(*t)) t++;
  sscanf(t,"%[A-z0-9_]*)",Class::interface_base);

};
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 96 "parser.lex"
{
  char *t=strchr(yytext,'=');
  t++;
  while (isspace(*t)) t++;
  sscanf(t,"%[A-z0-9_]*)",Class::broker_base);
};
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "parser.lex"
{
  char *t=strchr(yytext,'=');
  t++;
  while (isspace(*t)) t++;
  sscanf(t,"%[A-z0-9_]*)",Class::object_base);
};
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 113 "parser.lex"
{
  char *t1, *t2;
  sscanf(yytext+1, "%d", &linenumber);
  linenumber++;
  //  printf("LINE DIRECTIVE:line:%d in %s\n", linenumber,filename);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  //  yylval=PutToken(yytext);
  //  return DIRECTIVE;  
};
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 123 "parser.lex"
{
  char *t1, *t2;
  sscanf(yytext+1, "%d", &linenumber);
  t1=strchr(yytext,'"');
  if (t1!=NULL)
    {
      t1++;
      t2=strchr(t1,'"');
      if (t2!=NULL)
	{
	  *t2=0;
	  strcpy(filename,t1);
	  if (thisCodeFile->GetFileName()==NULL) thisCodeFile->SetFileName(filename); 
	  *t2='"';
	}
    }
  //  printf("LINE DIRECTIVE:line:%d in %s\n", linenumber,filename);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  //  yylval=PutToken(yytext);
  //  return DIRECTIVE;  
};
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 145 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  //  yylval=PutToken(yytext);
  //  return DIRECTIVE;  
};
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 151 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  linenumber+=CountLine(yytext);

  yylval=PutToken(yytext);
  return STRING;

};
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 160 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  linenumber+=CountLine(yytext);

  yylval=PutToken(yytext);
  return STRING;
};
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 169 "parser.lex"
{
  char clname[256];
  char methname[256];

  int len=0;
  char *tmp=yytext;
  while (!isspace(*tmp) && *tmp!=':') 
    {
      clname[len]=*tmp;
      classname[len]=*tmp;
      tmp++;
      len++;
    }
  clname[len]=0;
  classname[len]=0;
  
 if (thisCodeFile->FindClass(clname)!=NULL)
    {
      while (isspace(*tmp) || *tmp==':') tmp++;
      bool constructor=paroc_utils::isEqual(clname,tmp);
      
      char postfix[32]="__parocobj";
      int len=strlen(clname);
      int len1=strlen(postfix);
      othercodes.InsertAt(-1,clname,len);
      othercodes.InsertAt(-1,postfix,len1);
      othercodes.InsertAt(-1,yytext+len,strlen(yytext)-len);
      othercodes.InsertAt(-1,postfix,len1);
    }
  else
    {
      othercodes.InsertAt(-1,yytext,strlen(yytext));
    }
  linenumber+=CountLine(tmp);
};
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 205 "parser.lex"
{
  char clname[256];
  char methname[256];
  bool shouldreturn=true;
  char newyytext[1024];
  char thisBuf[1024];

  int len=0;
  char *tmp=yytext;
  while (!isspace(*tmp) && *tmp!=':') 
    {
      clname[len]=*tmp;
      classname[len]=*tmp;
      tmp++;
      len++;
    }
  clname[len]=0;
  classname[len]=0;
  
  //  printf("Method of class [%s]\n",clname);

  if (thisCodeFile->FindClass(clname)!=NULL)
    {
      while (isspace(*tmp) || *tmp==':') tmp++;
      bool constructor=paroc_utils::isEqual(clname,tmp);
      sprintf(newyytext,"%s__parocobj%s",clname,yytext+len);
      othercodes.InsertAt(-1,newyytext,strlen(newyytext));
      //Create the string to be inserted in every paroc_object constructor
      sprintf(thisBuf, "__POPThis_%s = new %s(GetAccessPointForThis());", clname, clname);

      if (constructor)
	{
	  shouldreturn=false;
	  char postfix[]="__parocobj";
	  int len1=strlen(postfix);
	  othercodes.InsertAt(-1,postfix,len1);

	  char buf[10240];
	  int n=ReadUntil((char*)");{", buf, 10240);
	  othercodes.InsertAt(-1,buf,n);
    

	  linenumber+=CountLine(buf);
	  if (n && buf[n-1]==')'){
	     n=ReadUntil((char*)":;{", buf, 10240);
	     othercodes.InsertAt(-1,buf,n);
	     linenumber+=CountLine(buf);
     }
	  if (n && buf[n-1]==':'){
	      while (1)
		{
		  //extract base class name
		  n=ReadUntil((char*)"({;",buf,10240);
		  if (!n) break;

		  linenumber+=CountLine(buf);
		  if (buf[n-1]!='(')
		    {
		      fprintf(stderr, "ERROR: %s:%d: Bad base class initialization\n",filename, linenumber);
		      exit(1);
		    }
		  sscanf(buf," %[_a-zA-Z0-9]",clname);

		  if (thisCodeFile->FindClass(clname)!=NULL)
		    {
		      char *t=strstr(buf,clname)+ strlen(clname);
		      othercodes.InsertAt(-1,buf,t-buf);
		      othercodes.InsertAt(-1,postfix,len1);
		      othercodes.InsertAt(-1,t,strlen(t));
		    }
		  else othercodes.InsertAt(-1,buf,n);
		  //Extract parametters...
		  
		  n=ReadUntil((char*)"){;",buf,10240);
		  othercodes.InsertAt(-1,buf,n);
		  if (!n || buf[n-1]!=')') break;

		  //Extract separators...
		  n=ReadUntil((char*)",{;",buf,10240);
		  othercodes.InsertAt(-1,buf,n);
		  if (!n || buf[n-1]!=',') break;
		}
	    }
     //Print the THIS handling string line
     othercodes.InsertAt(-1, thisBuf, strlen(thisBuf));
     
	}
    }
  else
    {
      strcpy(newyytext,yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
    }
  linenumber+=CountLine(tmp);

  if (shouldreturn)
    {
      yylval=PutToken(newyytext);
      return ID;
    }
};
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 308 "parser.lex"
{
  linenumber++; 
  othercodes.InsertAt(-1,yytext,strlen(yytext));
};
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 313 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  /*  printf(" class keyword\n");*/
  yylval=PutToken(char(100));
  
  startPos=othercodes.GetSize();
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PARCLASS_KEYWORD;
};
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 329 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return CLASS_KEYWORD;

};
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 336 "parser.lex"
{
	yylval=PutToken(yytext);
	othercodes.InsertAt(-1,yytext,strlen(yytext));
	return ENUM;
};
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 342 "parser.lex"
{
	yylval=PutToken(yytext);
	othercodes.InsertAt(-1,yytext,strlen(yytext));
	return ENUM;
};
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 348 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return CLASSID;
};
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 361 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return AUTO_KEYWORD;
};
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 367 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return REGISTER_KEYWORD;
}; 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 374 "parser.lex"
{
  if (!insideClass) othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PUBLIC_KEYWORD;
};
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 378 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PRIVATE_KEYWORD;
};
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 382 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PROTECTED_KEYWORD;
};
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 388 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return VIRTUAL_KEYWORD;
};
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 393 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return CONST_KEYWORD;
};
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 398 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return STRUCT_KEYWORD;
};
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 404 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }
  else
    {
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return SYNC_INVOKE;
    }
}; 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 419 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return ASYNC_INVOKE;
};
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 431 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return INPUT;
};
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 443 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return OUTPUT;
};
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 455 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return CONCURRENT;
};
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 468 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return SEQUENTIAL;
};
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 480 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      char *yycopy=strdup(yytext+5);
      int len=strlen(yycopy);
      yylval=PutToken((char*)"mutex");
      othercodes.InsertAt(-1,yytext,5);
      for (char *t=yycopy+len-1;t!=yycopy;t--) unput(*t); 
      free(yycopy);
      return ID;
      
      //      othercodes.InsertAt(-1,yytext,strlen(yytext));
    }
  else
    {
      char str[256];
      int len=strlen(yytext)-6;
      sprintf(str," { paroc_mutex_locker _paroc_mutex%d(_paroc_omutex); ",mutexCount++); 
      othercodes.InsertAt(-1,str,strlen(str));
      othercodes.InsertAt(-1,yytext+5,len);
    }
  linenumber+=CountLine(yytext+5);
};
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 504 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return MUTEX;

};
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 517 "parser.lex"
{

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return SCOPE;
};
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 523 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return HIDDEN;  
};
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 535 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  yylval=PutToken(char(USERPROC));
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PROC;
};
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 547 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  yylval=PutToken(char(PARAMSIZE));
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return SIZE;
};
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 560 "parser.lex"
{

	/* This part of parser is possible source of wrong "this" handling */
	Class *cl = thisCodeFile->FindClass(classname);
	bool insertNormalThis = true;
	
	if (cl!=NULL)
	{
      //If the class is a parclass, replace THIS keyword by the Interface pointer __POPThis_ClassName
      if(cl->IsParClass()){
         othercodes.InsertAt(-1,"__POPThis_", strlen("__POPThis_"));
			othercodes.InsertAt(-1,cl->GetName(),strlen(cl->GetName()));
			insertNormalThis = false;
		}
	}
	
	if(insertNormalThis)
	{
		othercodes.InsertAt(-1,yytext,strlen(yytext));
	}
	
	
	/*
	yylval=PutToken(yytext);
	othercodes.InsertAt(-1,"this",strlen("this"));
 	
	printf("handle at Flex -> ");
	return THIS_KEYWORD;*/
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 590 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 597 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 604 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 611 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 618 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 625 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 633 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 640 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 647 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(TYPEDEF_KEYWORD);
};
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 652 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID);
};
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 658 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (INTEGER);
};
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 664 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (REAL);  
};
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 672 "parser.lex"
;
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 673 "parser.lex"
{
  linenumber+=CountLine(yytext);
} ;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 677 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (AND_OP);    
};
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 683 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (OR_OP);    
};
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 689 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (EQUAL_OP);    
};
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 695 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (NOTEQUAL_OP);    
};
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 701 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (GREATEREQUAL_OP);    
};
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 707 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (LESSEQUAL_OP);    
};
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 713 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (NONSTRICT_OD_OP);    
};
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 720 "parser.lex"
{ 
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return yytext[0]; 
};
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 725 "parser.lex"
{
  return EOFCODE;
};
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 728 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return yytext[0];   
};
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 733 "parser.lex"
ECHO;
	YY_BREAK
#line 2051 "parser.yy.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 309 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 309 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 308);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 733 "parser.lex"



int yylex();

int PutToken(char *str)
{
  assert(str!=NULL);
  int len=strlen(str)+1;
  if (tokenpos<tokenbuf || tokenpos+len>=tokenbuf+10000) tokenpos=tokenbuf;
  strcpy(tokenpos,str);
  int ret=tokenpos-tokenbuf;
  tokenpos+=len;
  return ret;
}


int PutToken(char chr)
{
  int len=2;
  if (tokenpos<tokenbuf || tokenpos+len>=tokenbuf+10000) tokenpos=tokenbuf;
  int ret=tokenpos-tokenbuf;

  tokenpos[0]=chr;
  tokenpos[1]=0;
  tokenpos+=2;
  return ret;
}


char *GetToken(int yyval)
{
  assert(yyval>=0 && yyval<10000);
  return (tokenbuf+yyval);
}


int CountLine(char *str)
{
  if (str==NULL) return 0;
  int n=0;
  for (;*str!=0;str++) if (*str=='\n') n++;
  return n;
}

int ReadUntil(char *sep, char *buf, int sz)
{
  if (sz<=1)
    {
      printf("Buffer size (%d) error\n", sz);
      if (sz==1) *buf=0;
      return 0;
    }
 
  char *tmp=buf;
  int ch=1;
  int bracket=0;

  while (strchr(sep,ch)==NULL && ch!=EOF)
    {
      ch=yyinput();
      *tmp=ch;
      tmp++;
      sz--;
      if (sz<=1)
	{
	  *tmp=0;
	  return (tmp-buf);
	}
      if (ch=='"')
	{
	  int n;
	  while ((n=ReadUntil((char*)"\"", tmp,sz))>0 && tmp[n-2]=='\\');
	}
      else if (ch=='\'')
	{
	  int n;
	  while ((n=ReadUntil((char*)"\'", tmp,sz))>0 && tmp[n-2]=='\\');
	}
      else if (ch=='(') bracket++;
      else if (ch==')')
	{
	  bracket--;
	  if (bracket>0) ch=1;
	}
    }
  
  *tmp=0;
  return (tmp-buf);
}


bool IsSystemHeader(char *fname)
{
  char system_header[]="/usr/include";
  if (fname==NULL) return false;
  int len=strlen(fname);

  //  return strcmp(fname+len-2,".h")==0;

  return strncmp(fname,system_header,strlen(system_header))==0;
}


