#line 2 "parser.yy.cc"

#line 4 "parser.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[315] =
    {   0,
        0,    0,   65,   63,    1,   14,   62,   62,   62,   62,
       62,   63,   63,   51,   62,   63,   62,   63,   63,   62,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   62,    9,   62,    1,   58,
        0,   10,    0,   55,    0,   11,    0,   52,    0,   53,
        0,   51,   36,   60,   57,   59,    0,   61,    0,    0,
        0,   50,    0,   50,   50,   50,   50,   50,   50,   30,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   56,    9,    9,    9,    9,
        0,    0,   10,    0,   11,    0,    0,    0,    0,   53,

        0,    0,   50,   50,   50,   50,   50,   50,   50,   50,
       31,   50,   50,   50,   50,   50,   33,   50,   50,   50,
       50,   50,   50,   50,   50,    9,    7,    9,    0,   52,
       54,    0,    0,   13,    0,   50,   50,   20,   50,   32,
       50,   17,   50,   50,   50,   50,   38,   50,   50,   50,
       50,   39,   50,   28,   40,   50,   50,   50,    9,    9,
        0,    2,   13,    0,    0,   12,   50,   29,   16,   26,
       35,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,    9,    0,    8,    9,    0,    0,   12,   50,
       50,    0,   34,   50,   50,   50,   50,   22,   50,   50,

       27,   50,   50,   50,    8,    8,    9,    0,    0,   50,
       50,   50,   50,   23,   50,   50,    0,   49,   50,   25,
        8,    9,    0,   37,   19,   50,   15,   50,   21,    0,
        0,    0,    0,   50,    9,    9,    9,    9,    0,   18,
       24,    0,    0,    0,    0,    0,    9,    9,    9,    0,
        0,   42,    0,    0,    0,    0,    0,    0,    9,    9,
        9,    0,   45,   44,    0,    0,    0,    0,    0,    9,
        9,    9,    0,   47,    0,   41,    0,    0,    9,    9,
        9,    0,   46,   43,    0,    9,    9,    9,    0,    3,
       48,    9,    9,    9,    9,    9,    3,    9,    5,    9,

        9,    6,    5,    5,    9,    6,    6,    9,    9,    9,
        4,    4,    4,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    4,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   29,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   28,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    2,    2,    3,    1,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    6,
        7,    1,    1,    1,    1,    1,    1,    8,    8,    1,
        1,    1,    1,    8,    1,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1,    9
    } ;

static yyconst flex_int16_t yy_base[331] =
    {   0,
        0,   58,  801, 1309,   64, 1309,  775,   62, 1309,  788,
       58,  777,   56,   53,  775,  771,  770,  768,   74,   77,
       80,   84,   88,   96,  100,  104,  108,  111,  120,  131,
      115,  122,  127,  101,   83,  728,  128,  157,   94, 1309,
      114, 1309,  134, 1309,   63, 1309,  158,  153,  775,    0,
      768,  154, 1309, 1309, 1309, 1309,  188, 1309,  192,  750,
      195,  149,  758,  164,  165,  170,  174,  179,  178,  183,
      193,  197,  201,  202,  215,  224,  228,  226,  230,  238,
      239,  249,  253,  260,  262, 1309,    0,  249,  297,  719,
      308,  735,  182,  216,  256,  288,  748,  751,  744,    0,

      717,  318,  287,  288,  289,  293,  297,  312,  316,  318,
      325,  337,  327,  341,  351,  355,  349,  364,  370,  356,
      365,  378,  388,  383,  393,  238, 1309,  703,  317,  708,
     1309,  664,  324,  687,  448,  401,  407,  402,  411,  406,
      417,  425,  430,  438,  440,  444,  446,  465,  454,  459,
      480,  453,  481,  472,  486,  487,  488,  493,  326,  660,
      633, 1309,  655,  652,  548,    0,  509,  502,  511,  517,
      557,  518,  527,  532,  539,  543,  548,  554,  553,  558,
      564,  566,  330,  664,    0,  594,  602,  621,    0,  576,
      590,  633, 1309,  585,  591,  612,  603,  597,  621,  660,

      613,  619,  631,  642,    0,    0,  595,  587,  688,  644,
      643,  650,  665,  669,  671,  673,  710,  679,  681,  680,
        0,  701,  571,  687,  694,  706,  705,  717,  713,  562,
      542,  536,  539,  772,  741,  519,  517,  520,  509,  724,
      731,  495,  472,  455,  453,  779,  435,  429,  434,  437,
      422, 1309,  429,  416,  425,  384,  380,  382,  376,  375,
      349,  383, 1309, 1309,  321,  331,  311,  315,  312,  317,
      285,  270,  270, 1309,  254, 1309,  261,  244,  210,  199,
      157,  205, 1309, 1309,  149,  392,  167,  432,  150,    0,
     1309,  508,  831,  100,  511,  889,    0,    0,  947,   90,

        0, 1005,  123,    0,  573,  113,    0,  627, 1063,    0,
     1121,   69,    0, 1309, 1181, 1190, 1198, 1206, 1215, 1224,
     1232, 1236, 1243, 1251, 1255, 1263, 1272, 1281, 1290, 1299
    } ;

static yyconst flex_int16_t yy_def[331] =
    {   0,
      314,    1,  314,  314,  314,  314,  314,  315,  314,  314,
      316,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
       30,   30,   30,   30,   30,  314,  318,  314,  314,  314,
      315,  314,  315,  314,  316,  314,  316,  314,  319,  320,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,   30,  314,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,  314,  318,  318,  318,  318,
      314,  314,  315,  315,  316,  316,  314,  319,  314,  320,

      314,  321,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,  318,  314,  318,  314,  314,
      314,  314,  321,  322,  323,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,  324,  318,
      314,  314,  322,  314,  323,  325,   30,   30,   30,   30,
      317,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,  324,  326,  327,  318,  314,  321,  325,   30,
       30,  314,  314,   30,   30,   30,   30,   30,   30,  317,

       30,   30,   30,   30,  328,  327,  318,  314,  321,   30,
       30,   30,   30,   30,   30,   30,  314,   30,   30,   30,
      328,  318,  314,   30,   30,   30,   30,   30,   30,  314,
      314,  314,  314,  317,  318,  318,  318,  318,  314,   30,
       30,  314,  314,  314,  314,  314,  318,  318,  318,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  318,  318,
      318,  314,  314,  314,  314,  314,  314,  314,  314,  318,
      318,  318,  314,  314,  314,  314,  314,  314,  318,  318,
      318,  329,  314,  314,  314,  318,  318,  318,  329,  330,
      314,  318,  318,  318,  318,  318,  330,  293,  293,  318,

      296,  296,  318,  299,  318,  318,  302,  318,  318,  309,
      309,  318,  311,    0,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314
    } ;

static yyconst flex_int16_t yy_nxt[1374] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,    9,    9,   10,
       11,    9,    9,    9,    9,    9,    9,   12,   13,   14,
       15,    9,   16,   17,   18,   19,   20,   21,   21,    9,
        4,    9,    9,   22,    9,   23,   21,   24,   21,   25,
       21,   21,   21,   26,   21,   21,   21,   27,   28,   29,
       30,   21,   31,   32,   33,   34,   35,   21,   21,   21,
        9,   36,    9,    9,   37,   39,   39,   42,   46,   49,
       51,  312,   52,   46,   50,   57,   57,   57,   59,   59,
       59,   61,   61,   61,   38,   61,   61,   61,   47,   61,
       61,   61,   43,   47,   58,   39,   39,   61,   61,   61,

       63,   61,   61,   61,   63,   61,   61,   61,   63,   61,
       61,   61,   61,   61,   61,  306,   63,   64,   62,   42,
       63,   61,   61,   61,   63,  303,   85,   60,   63,  305,
       88,   63,   61,   61,   61,   62,   62,  300,   62,   93,
       63,   65,   67,   66,   43,   68,   72,   89,   69,   84,
       62,   63,   70,   62,   77,  290,   62,   62,   91,   91,
       91,   78,   62,   71,   94,   79,   74,   62,   95,   82,
       62,   51,   48,   52,   62,   73,   80,   62,   90,   62,
       81,   97,   62,   75,   62,   83,   76,   42,   96,   57,
       57,   57,   97,   59,   59,   59,   61,   61,   61,   62,

       62,   62,  294,  291,   62,   62,  103,   92,   58,  106,
      290,  288,   43,   62,   62,   63,   62,   62,   62,   62,
       62,   93,   62,  104,  105,   62,   62,  107,   62,   62,
       62,   62,   62,  108,   62,   62,   62,   62,   62,  287,
      126,  127,   60,  159,  110,   62,   94,  109,   62,   62,
       62,   88,   62,   62,  112,  111,   62,   62,  113,   62,
      115,   62,  286,   62,  114,   62,   46,   62,   89,  116,
       62,  118,  273,   62,   62,  282,   62,  117,   62,   62,
       62,   62,   62,   62,   62,   62,   47,  121,   62,  119,
      120,   62,  122,   62,   62,   62,  285,   62,   95,  126,

      127,   62,  284,  123,   62,   62,  283,  281,   62,   91,
       91,   91,   62,  124,  125,   62,   89,   62,   96,  133,
      133,  133,   62,   62,   62,  133,  133,  133,   62,  184,
      136,  185,   62,  184,  140,  185,  137,  280,  138,   62,
       62,   62,   62,   62,   62,   62,  139,   62,   62,   62,
      141,   62,   62,   62,  132,  143,  279,  144,   92,  142,
       62,  278,   62,  277,   62,  276,  275,   62,   62,  161,
       62,   62,   62,   62,  145,  274,   62,   62,  147,   62,
       62,  135,   62,  146,   62,  273,   62,  135,  272,   62,
       62,   62,   62,   62,  292,  148,   62,  149,  150,   62,

       62,   62,  154,   62,   62,   62,   62,   62,   62,  152,
       62,  153,  151,   62,  271,  293,   62,   62,   62,   62,
       62,  270,   62,   62,  269,   62,  157,  156,   62,  268,
       62,  155,  267,   62,  295,   62,   62,   62,   62,  167,
       62,   62,   62,   62,  168,   62,   62,  158,   62,  165,
      165,  165,   62,   62,   62,  296,   62,   62,   62,   62,
       62,   62,   62,   62,  169,   62,   62,  266,  265,   62,
      264,  170,   62,   62,  263,   62,  262,   62,  261,  174,
       62,   62,   62,  260,  259,   62,  173,  171,   62,   62,
       62,  172,   62,   62,   62,   62,   62,  176,   62,   62,

       62,   62,  254,  253,  175,   62,   62,   62,   62,   62,
      292,   62,  177,  295,   62,   62,   62,   62,  179,  178,
       62,   62,   62,   62,   62,  180,  252,   62,   62,  181,
      251,  293,   62,   62,  296,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,  190,  182,  165,
      165,  165,   62,   62,   62,  250,  249,   62,  192,  192,
      192,   62,  195,   62,   62,  248,  191,   62,  194,   62,
       62,  247,   62,   62,   62,  308,  197,   63,   62,   62,
      198,  245,   62,   62,   62,  244,  196,   62,   62,   62,
      243,   62,  200,   62,   62,   62,  309,  202,   62,   62,

       62,  204,  199,   62,  242,   62,   62,  201,   62,   62,
       62,   62,  203,   62,  239,  210,   62,  193,   62,   62,
      212,   62,  209,  209,  209,   62,   62,  223,   62,  308,
      222,   62,   62,  211,  192,  192,  192,   62,   62,  208,
       62,  207,   62,   62,  213,   62,   62,   62,   62,   62,
      309,  214,   62,   63,   62,   62,   62,  215,   62,  218,
      216,  217,  217,  217,   62,   62,   62,   62,   62,  205,
      219,   62,  188,   62,   62,  164,   62,   62,   62,   62,
       63,  225,  187,   62,  314,   62,   62,  226,  220,  209,
      209,  209,  224,  193,   62,   62,   62,   62,   62,   62,

       62,  186,   62,  235,   62,   62,   62,  164,   62,  162,
      228,  217,  217,  217,   62,   62,   62,   62,  227,  234,
       62,   62,   62,   62,   62,  229,   62,  130,   62,   62,
       63,   62,   62,   62,   62,   62,   62,  236,  160,   62,
       62,   62,   62,  235,  237,  240,   62,  230,   62,   62,
      238,  314,   62,  231,  132,  241,  232,   62,   62,   62,
       62,   62,  131,  233,   99,   62,   62,  130,   62,   62,
      129,  128,   62,  246,  246,  246,   62,  236,  102,   62,
      246,  246,  246,   62,  237,  101,   62,   48,   99,   86,
      238,   56,   63,   55,   54,   53,   48,   44,   40,   63,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  255,  314,  314,  314,
      314,  314,  256,  314,  314,  257,  314,  314,  314,  314,
      314,  314,  258,  298,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  299,  299,
      314,  314,  314,  314,  299,  314,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  301,  314,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  302,  302,  314,  314,
      314,  314,  302,  314,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  303,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  304,  314,  314,  314,
      314,  314,  314,  314,  304,  304,  314,  314,  314,  314,
      304,  314,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,

      304,  304,  304,  304,  304,  304,  304,  306,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  307,  314,  314,  314,  314,  314,
      314,  314,  307,  307,  314,  314,  314,  314,  307,  314,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  310,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      311,  311,  314,  314,  314,  314,  311,  314,  311,  311,

      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  312,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      313,  314,  314,  314,  314,  314,  314,  314,  313,  313,
      314,  314,  314,  314,  313,  314,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       45,   45,   45,  314,   45,   45,   45,   45,   45,   62,

       62,  314,  314,   62,   62,   62,   87,   87,  314,   87,
       87,   87,   87,   87,   87,   98,   98,   98,  314,  314,
       98,   98,   98,   98,  100,  100,  314,  100,  100,  100,
      100,  100,  100,  134,  134,  314,  314,  314,  314,  134,
      134,  163,  163,  163,  166,  166,  314,  314,  314,  314,
      166,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      189,  314,  189,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  206,  206,  314,  206,  206,  206,  206,  206,
      206,  221,  221,  314,  221,  221,  221,  221,  221,  221,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  297,

      297,  314,  297,  297,  297,  297,  297,  297,    3,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314
    } ;

static yyconst flex_int16_t yy_chk[1374] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    5,    5,    8,   11,   13,
       14,  312,   14,   45,   13,   19,   19,   19,   20,   20,
       20,   21,   21,   21,    2,   22,   22,   22,   11,   23,
       23,   23,    8,   45,   19,   39,   39,   24,   24,   24,

       21,   25,   25,   25,   22,   26,   26,   26,   23,   27,
       27,   27,   28,   28,   28,  306,   24,   22,   35,   41,
       25,   29,   29,   29,   26,  303,   35,   20,   27,  300,
       37,   28,   30,   30,   30,   35,   34,  294,   35,   43,
       29,   23,   24,   23,   41,   24,   28,   37,   25,   34,
       31,   30,   26,   34,   31,  289,   34,   32,   38,   38,
       38,   32,   33,   27,   43,   32,   30,   31,   47,   33,
       31,   52,   48,   52,   32,   29,   32,   32,   37,   33,
       32,   48,   33,   30,   62,   33,   30,   93,   47,   57,
       57,   57,   48,   59,   59,   59,   61,   61,   61,   64,

       65,   62,  287,  285,   62,   66,   64,   38,   57,   67,
      282,  281,   93,   69,   68,   61,   64,   65,   70,   64,
       65,   94,   66,   65,   66,   66,   67,   68,   71,   67,
       69,   68,   72,   69,   68,   70,   73,   74,   70,  280,
      126,  126,   59,  126,   72,   71,   94,   71,   71,   72,
       75,   88,   72,   73,   74,   73,   73,   74,   75,   76,
       76,   78,  279,   77,   75,   79,   95,   75,   88,   77,
       75,   79,  273,   80,   81,  273,   76,   78,   78,   76,
       77,   78,   79,   77,   82,   79,   95,   81,   83,   79,
       80,   81,   82,   80,   81,   84,  278,   85,   96,   89,

       89,   82,  277,   83,   82,   83,  275,  272,   83,   91,
       91,   91,   84,   84,   85,   84,   89,   85,   96,  102,
      102,  102,  103,  104,  105,  133,  133,  133,  106,  159,
      103,  159,  107,  183,  107,  183,  104,  271,  105,  103,
      104,  105,  103,  104,  105,  106,  106,  108,  106,  107,
      107,  109,  107,  110,  129,  109,  270,  110,   91,  108,
      111,  269,  113,  268,  108,  267,  266,  108,  109,  129,
      110,  109,  112,  110,  112,  265,  114,  111,  114,  113,
      111,  102,  113,  113,  117,  262,  115,  133,  261,  112,
      116,  120,  112,  114,  286,  114,  114,  115,  116,  118,

      121,  117,  121,  115,  117,  119,  115,  116,  120,  119,
      116,  120,  118,  122,  260,  286,  118,  121,  124,  118,
      121,  259,  119,  123,  258,  119,  124,  123,  125,  257,
      122,  122,  256,  122,  288,  124,  136,  138,  124,  136,
      123,  140,  137,  123,  137,  125,  139,  125,  125,  135,
      135,  135,  141,  136,  138,  288,  136,  138,  140,  137,
      142,  140,  137,  139,  139,  143,  139,  255,  254,  141,
      253,  141,  141,  144,  251,  145,  250,  142,  249,  146,
      142,  147,  143,  248,  247,  143,  145,  143,  152,  149,
      144,  144,  145,  144,  150,  145,  146,  149,  147,  146,

      148,  147,  245,  244,  148,  152,  149,  154,  152,  149,
      292,  150,  150,  295,  150,  151,  153,  148,  153,  151,
      148,  155,  156,  157,  154,  156,  243,  154,  158,  157,
      242,  292,  151,  153,  295,  151,  153,  168,  155,  156,
      157,  155,  156,  157,  167,  158,  169,  167,  158,  165,
      165,  165,  170,  172,  168,  239,  238,  168,  171,  171,
      171,  167,  173,  169,  167,  237,  169,  174,  172,  170,
      172,  236,  170,  172,  175,  305,  175,  171,  176,  173,
      176,  233,  173,  177,  174,  232,  174,  174,  179,  178,
      231,  175,  178,  180,  175,  176,  305,  180,  176,  181,

      177,  182,  177,  177,  230,  179,  178,  179,  179,  178,
      180,  190,  181,  180,  223,  190,  181,  171,  182,  181,
      194,  182,  188,  188,  188,  191,  195,  208,  190,  308,
      207,  190,  198,  191,  192,  192,  192,  194,  197,  187,
      194,  186,  191,  195,  195,  191,  195,  196,  201,  198,
      308,  196,  198,  192,  202,  197,  199,  197,  197,  202,
      199,  200,  200,  200,  196,  201,  203,  196,  201,  184,
      203,  202,  164,  199,  202,  163,  199,  204,  211,  210,
      200,  211,  161,  203,  188,  212,  203,  212,  204,  209,
      209,  209,  210,  192,  204,  211,  210,  204,  211,  210,

      213,  160,  212,  222,  214,  212,  215,  134,  216,  132,
      215,  217,  217,  217,  218,  220,  219,  213,  213,  219,
      213,  214,  224,  215,  214,  216,  215,  130,  216,  225,
      217,  218,  220,  219,  218,  220,  219,  222,  128,  224,
      227,  226,  224,  235,  222,  226,  225,  217,  229,  225,
      222,  209,  228,  217,  101,  228,  217,  227,  226,  240,
      227,  226,   99,  217,   98,  229,  241,   97,  229,  228,
       92,   90,  228,  234,  234,  234,  240,  235,   63,  240,
      246,  246,  246,  241,  235,   60,  241,   51,   49,   36,
      235,   18,  234,   17,   16,   15,   12,   10,    7,  246,

        3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  246,    0,    0,    0,
        0,    0,  246,    0,    0,  246,    0,    0,    0,    0,
        0,    0,  246,  293,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  293,  293,
        0,    0,    0,    0,  293,    0,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  296,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  296,  296,    0,    0,
        0,    0,  296,    0,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  299,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  299,    0,    0,    0,
        0,    0,    0,    0,  299,  299,    0,    0,    0,    0,
      299,    0,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,

      299,  299,  299,  299,  299,  299,  299,  302,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  302,    0,    0,    0,    0,    0,
        0,    0,  302,  302,    0,    0,    0,    0,  302,    0,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  309,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      309,  309,    0,    0,    0,    0,  309,    0,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  311,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      311,    0,    0,    0,    0,    0,    0,    0,  311,  311,
        0,    0,    0,    0,  311,    0,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      316,  316,  316,    0,  316,  316,  316,  316,  316,  317,

      317,    0,    0,  317,  317,  317,  318,  318,    0,  318,
      318,  318,  318,  318,  318,  319,  319,  319,    0,    0,
      319,  319,  319,  319,  320,  320,    0,  320,  320,  320,
      320,  320,  320,  321,  321,    0,    0,    0,    0,  321,
      321,  322,  322,  322,  323,  323,    0,    0,    0,    0,
      323,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      325,    0,  325,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  327,  327,    0,  327,  327,  327,  327,  327,
      327,  328,  328,    0,  328,  328,  328,  328,  328,  328,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  330,

      330,    0,  330,  330,  330,  330,  330,  330,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser.lex"
#line 2 "parser.lex"

#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <ctype.h>
#include "parser.tab.h"
#include "parser.h"
#include "paroc_utils.h"
#include "debug.h"

  int c;
  int linenumber=0;
  char filename[1024];
  char classname[1024];
  int mutexCount=0;
  int dummyCount=0;

  extern CArrayCharPtr searchpath, sources;
  extern CodeFile *thisCodeFile;

  CArrayChar othercodes(0,32536);
  bool insideClass;
  int startPos=-1;

  /*
#if !defined (YYSTYPE)
#define YYSTYPE long
#endif
  */

  extern YYSTYPE yylval;
  extern char token[];
  extern int yylex(void);

  char tokenbuf[32000];
  char *tokenpos;

  int  PutToken(char *str);
  int PutToken(char chr);
  char *GetToken(int yyval);
  int CountLine(char *str);
  bool IsSystemHeader(char *fname);

  int ReadUntil(char *sep, char *output, int sz);
   
#line 906 "parser.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 59 "parser.lex"


#line 1094 "parser.yy.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 315 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1309 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 61 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
};
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 65 "parser.lex"
{
  startPos=othercodes.GetSize();
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PACK_KEYWORD;
};
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 71 "parser.lex"
{
  char *t1, *t2;
  t1=strchr(yytext,'"');
  if (t1!=NULL)
    {
      t1++;
      t2=strrchr(t1,'"');
      if (t2!=NULL)
	{
	  *t2=0;
	  strcpy(filename,t1);
	  thisCodeFile->SetFileName(filename); 
	  *t2='"';
	}
    }
  //  printf("LINE DIRECTIVE:line:%d in %s\n", linenumber,filename);
};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 89 "parser.lex"
{
  char *t=strchr(yytext,'=');
  t++;
  while (isspace(*t)) t++;
  sscanf(t,"%[A-z0-9_]*)",Class::interface_base);

};
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 96 "parser.lex"
{
  char *t=strchr(yytext,'=');
  t++;
  while (isspace(*t)) t++;
  sscanf(t,"%[A-z0-9_]*)",Class::broker_base);
};
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "parser.lex"
{
  char *t=strchr(yytext,'=');
  t++;
  while (isspace(*t)) t++;
  sscanf(t,"%[A-z0-9_]*)",Class::object_base);
};
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 113 "parser.lex"
{
  char *t1, *t2;
  sscanf(yytext+1, "%d", &linenumber);
  linenumber++;
  //  printf("LINE DIRECTIVE:line:%d in %s\n", linenumber,filename);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  //  yylval=PutToken(yytext);
  //  return DIRECTIVE;  
};
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 123 "parser.lex"
{
  char *t1, *t2;
  sscanf(yytext+1, "%d", &linenumber);
  t1=strchr(yytext,'"');
  if (t1!=NULL)
    {
      t1++;
      t2=strchr(t1,'"');
      if (t2!=NULL)
	{
	  *t2=0;
	  strcpy(filename,t1);
	  if (thisCodeFile->GetFileName()==NULL) thisCodeFile->SetFileName(filename); 
	  *t2='"';
	}
    }
  //  printf("LINE DIRECTIVE:line:%d in %s\n", linenumber,filename);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  //  yylval=PutToken(yytext);
  //  return DIRECTIVE;  
};
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 145 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  //  yylval=PutToken(yytext);
  //  return DIRECTIVE;  
};
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 151 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  linenumber+=CountLine(yytext);

  yylval=PutToken(yytext);
  return STRING;

};
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 160 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  linenumber+=CountLine(yytext);

  yylval=PutToken(yytext);
  return STRING;
};
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 169 "parser.lex"
{
  char clname[256];
  char methname[256];

  int len=0;
  char *tmp=yytext;
  while (!isspace(*tmp) && *tmp!=':') 
    {
      clname[len]=*tmp;
      classname[len]=*tmp;
      tmp++;
      len++;
    }
  clname[len]=0;
  classname[len]=0;
  
 if (thisCodeFile->FindClass(clname)!=NULL)
    {
      while (isspace(*tmp) || *tmp==':') tmp++;
      bool constructor=paroc_utils::isEqual(clname,tmp);
      
      char postfix[32]="__parocobj";
      int len=strlen(clname);
      int len1=strlen(postfix);
      othercodes.InsertAt(-1,clname,len);
      othercodes.InsertAt(-1,postfix,len1);
      othercodes.InsertAt(-1,yytext+len,strlen(yytext)-len);
      othercodes.InsertAt(-1,postfix,len1);
    }
  else
    {
      othercodes.InsertAt(-1,yytext,strlen(yytext));
    }
  linenumber+=CountLine(tmp);
};
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 205 "parser.lex"
{
  char clname[256];
  char methname[256];
  bool shouldreturn=true;
  char newyytext[1024];
  char thisBuf[1024];

  int len=0;
  char *tmp=yytext;
  while (!isspace(*tmp) && *tmp!=':') 
    {
      clname[len]=*tmp;
      classname[len]=*tmp;
      tmp++;
      len++;
    }
  clname[len]=0;
  classname[len]=0;
  
  //  printf("Method of class [%s]\n",clname);

  if (thisCodeFile->FindClass(clname)!=NULL)
    {
      while (isspace(*tmp) || *tmp==':') tmp++;
      bool constructor=paroc_utils::isEqual(clname,tmp);
      sprintf(newyytext,"%s__parocobj%s",clname,yytext+len);
      othercodes.InsertAt(-1,newyytext,strlen(newyytext));
      //Create the string to be inserted in every paroc_object constructor
      sprintf(thisBuf, "__POPThis_%s = new %s(GetAccessPointForThis());", clname, clname);

      if (constructor)
	{
	  shouldreturn=false;
	  char postfix[]="__parocobj";
	  int len1=strlen(postfix);
	  othercodes.InsertAt(-1,postfix,len1);

	  char buf[10240];
	  int n=ReadUntil((char*)");{", buf, 10240);
	  othercodes.InsertAt(-1,buf,n);
    

	  linenumber+=CountLine(buf);
	  if (n && buf[n-1]==')'){
	     n=ReadUntil((char*)":;{", buf, 10240);
	     othercodes.InsertAt(-1,buf,n);
	     linenumber+=CountLine(buf);
     }
	  if (n && buf[n-1]==':'){
	      while (1)
		{
		  //extract base class name
		  n=ReadUntil((char*)"({;",buf,10240);
		  if (!n) break;

		  linenumber+=CountLine(buf);
		  if (buf[n-1]!='(')
		    {
		      fprintf(stderr, "ERROR: %s:%d: Bad base class initialization\n",filename, linenumber);
		      exit(1);
		    }
		  sscanf(buf," %[_a-zA-Z0-9]",clname);

		  if (thisCodeFile->FindClass(clname)!=NULL)
		    {
		      char *t=strstr(buf,clname)+ strlen(clname);
		      othercodes.InsertAt(-1,buf,t-buf);
		      othercodes.InsertAt(-1,postfix,len1);
		      othercodes.InsertAt(-1,t,strlen(t));
		    }
		  else othercodes.InsertAt(-1,buf,n);
		  //Extract parametters...
		  
		  n=ReadUntil((char*)"){;",buf,10240);
		  othercodes.InsertAt(-1,buf,n);
		  if (!n || buf[n-1]!=')') break;

		  //Extract separators...
		  n=ReadUntil((char*)",{;",buf,10240);
		  othercodes.InsertAt(-1,buf,n);
		  if (!n || buf[n-1]!=',') break;
		}
	    }
     //Print the THIS handling string line
     othercodes.InsertAt(-1, thisBuf, strlen(thisBuf));
     
	}
    }
  else
    {
      strcpy(newyytext,yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
    }
  linenumber+=CountLine(tmp);

  if (shouldreturn)
    {
      yylval=PutToken(newyytext);
      return ID;
    }
};
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 308 "parser.lex"
{
  linenumber++; 
  othercodes.InsertAt(-1,yytext,strlen(yytext));
};
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 313 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  /*  printf(" class keyword\n");*/
  yylval=PutToken(char(100));
  
  startPos=othercodes.GetSize();
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PARCLASS_KEYWORD;
};
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 329 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return CLASS_KEYWORD;

};
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 336 "parser.lex"
{
	yylval=PutToken(yytext);
	othercodes.InsertAt(-1,yytext,strlen(yytext));
	return ENUM;
};
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 342 "parser.lex"
{
	yylval=PutToken(yytext);
	othercodes.InsertAt(-1,yytext,strlen(yytext));
	return NAMESPACE;
};
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 348 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return CLASSID;
};
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 361 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return AUTO_KEYWORD;
};
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 367 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return REGISTER_KEYWORD;
}; 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 374 "parser.lex"
{
  if (!insideClass) othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PUBLIC_KEYWORD;
};
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 378 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PRIVATE_KEYWORD;
};
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 382 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PROTECTED_KEYWORD;
};
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 388 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return VIRTUAL_KEYWORD;
};
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 393 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return CONST_KEYWORD;
};
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 398 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return STRUCT_KEYWORD;
};
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 403 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }
  else
    {
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return SYNC_INVOKE;
    }
}; 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 418 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return ASYNC_INVOKE;
};
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 430 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return INPUT;
};
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 442 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return OUTPUT;
};
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 454 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return CONCURRENT;
};
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 467 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return SEQUENTIAL;
};
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 479 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      char *yycopy=strdup(yytext+5);
      int len=strlen(yycopy);
      yylval=PutToken((char*)"mutex");
      othercodes.InsertAt(-1,yytext,5);
      for (char *t=yycopy+len-1;t!=yycopy;t--) unput(*t); 
      free(yycopy);
      return ID;
      
      //      othercodes.InsertAt(-1,yytext,strlen(yytext));
    }
  else
    {
      char str[256];
      int len=strlen(yytext)-6;
      sprintf(str," { paroc_mutex_locker _paroc_mutex%d(_paroc_omutex); ",mutexCount++); 
      othercodes.InsertAt(-1,str,strlen(str));
      othercodes.InsertAt(-1,yytext+5,len);
    }
  linenumber+=CountLine(yytext+5);
};
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 503 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return MUTEX;

};
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 516 "parser.lex"
{

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return SCOPE;
};
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 522 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return HIDDEN;  
};
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 534 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  yylval=PutToken(char(USERPROC));
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return PROC;
};
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 546 "parser.lex"
{
  if (IsSystemHeader(filename))
    {
      yylval=PutToken(yytext);
      othercodes.InsertAt(-1,yytext,strlen(yytext));
      return ID;
    }

  yylval=PutToken(char(PARAMSIZE));
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return SIZE;
};
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 559 "parser.lex"
{

	/* This part of parser is possible source of wrong "this" handling */
	Class *cl = thisCodeFile->FindClass(classname);
	bool insertNormalThis = true;
	
	if (cl!=NULL)
	{
      //If the class is a parclass, replace THIS keyword by the Interface pointer __POPThis_ClassName
      if(cl->IsParClass()){
         othercodes.InsertAt(-1,"__POPThis_", strlen("__POPThis_"));
			othercodes.InsertAt(-1,cl->GetName(),strlen(cl->GetName()));
			insertNormalThis = false;
		}
	}
	
	if(insertNormalThis)
	{
		othercodes.InsertAt(-1,yytext,strlen(yytext));
	}
	
	
	/*
	yylval=PutToken(yytext);
	othercodes.InsertAt(-1,"this",strlen("this"));
 	
	printf("handle at Flex -> ");
	return THIS_KEYWORD;*/
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 589 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 596 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 603 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 610 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 617 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 624 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 632 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 639 "parser.lex"
{
  yylval=PutToken(yytext);
  linenumber+=CountLine(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID1);
};
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 646 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(TYPEDEF_KEYWORD);
};
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 651 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));  
  return(ID);
};
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 657 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (INTEGER);
};
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 663 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (REAL);  
};
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 671 "parser.lex"
;
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 672 "parser.lex"
{
  linenumber+=CountLine(yytext);
} ;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 676 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (AND_OP);    
};
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 682 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (OR_OP);    
};
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 688 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (EQUAL_OP);    
};
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 694 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (NOTEQUAL_OP);    
};
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 700 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (GREATEREQUAL_OP);    
};
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 706 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (LESSEQUAL_OP);    
};
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 712 "parser.lex"
{
  yylval=PutToken(yytext);
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return (NONSTRICT_OD_OP);    
};
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 719 "parser.lex"
{ 
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return yytext[0]; 
};
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 724 "parser.lex"
{
	return EOFCODE;
};
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 727 "parser.lex"
{
  othercodes.InsertAt(-1,yytext,strlen(yytext));
  return yytext[0];   
};
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 732 "parser.lex"
ECHO;
	YY_BREAK
#line 2058 "parser.yy.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 315 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 315 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 314);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 732 "parser.lex"



int yylex();

int PutToken(char *str)
{
  assert(str!=NULL);
  int len=strlen(str)+1;
  if (tokenpos<tokenbuf || tokenpos+len>=tokenbuf+10000) tokenpos=tokenbuf;
  strcpy(tokenpos,str);
  int ret=tokenpos-tokenbuf;
  tokenpos+=len;
  return ret;
}


int PutToken(char chr)
{
  int len=2;
  if (tokenpos<tokenbuf || tokenpos+len>=tokenbuf+10000) tokenpos=tokenbuf;
  int ret=tokenpos-tokenbuf;

  tokenpos[0]=chr;
  tokenpos[1]=0;
  tokenpos+=2;
  return ret;
}


char *GetToken(int yyval)
{
  assert(yyval>=0 && yyval<10000);
  return (tokenbuf+yyval);
}


int CountLine(char *str)
{
  if (str==NULL) return 0;
  int n=0;
  for (;*str!=0;str++) if (*str=='\n') n++;
  return n;
}

int ReadUntil(char *sep, char *buf, int sz)
{
  if (sz<=1)
    {
      printf("Buffer size (%d) error\n", sz);
      if (sz==1) *buf=0;
      return 0;
    }
 
  char *tmp=buf;
  int ch=1;
  int bracket=0;

  while (strchr(sep,ch)==NULL && ch!=EOF)
    {
      ch=yyinput();
      *tmp=ch;
      tmp++;
      sz--;
      if (sz<=1)
	{
	  *tmp=0;
	  return (tmp-buf);
	}
      if (ch=='"')
	{
	  int n;
	  while ((n=ReadUntil((char*)"\"", tmp,sz))>0 && tmp[n-2]=='\\');
	}
      else if (ch=='\'')
	{
	  int n;
	  while ((n=ReadUntil((char*)"\'", tmp,sz))>0 && tmp[n-2]=='\\');
	}
      else if (ch=='(') bracket++;
      else if (ch==')')
	{
	  bracket--;
	  if (bracket>0) ch=1;
	}
    }
  
  *tmp=0;
  return (tmp-buf);
}


bool IsSystemHeader(char *fname)
{
  char system_header[]="/usr/include";
  if (fname==NULL) return false;
  int len=strlen(fname);

  //  return strcmp(fname+len-2,".h")==0;

  return strncmp(fname,system_header,strlen(system_header))==0;
}


