#include "popc_object.h"

// Generated by the compiler
class POPXMPObject_popcobject : virtual public POPC_Object {
public:
    POPXMPObject_popcobject();
    ~POPXMPObject_popcobject();
    void execute_xmp_1();
    void set_value(int val);
};