IF(CMAKE_USER_MAKE_RULES_OVERRIDE)
   INCLUDE(${CMAKE_USER_MAKE_RULE_OVERRIDE})
ENDIF(CMAKE_USER_MAKE_RULES_OVERRIDE)

IF(CMAKE_USER_MAKE_RULES_OVERRIDE_CXX)
   INCLUDE(${CMAKE_USER_MAKE_RULE_OVERRIDE_CXX})
ENDIF(CMAKE_USER_MAKE_RULES_OVERRIDE_CXX)


IF(NOT CMAKE_POPCPP_COMPILE_OBJECT)
   SET(CMAKE_POPCPP_COMPILE_OBJECT
    "<CMAKE_POPCPP_COMPILER>  <FLAGS> -object -o <OBJECT> <SOURCE>")
   SET(CMAKE_POPCPP_COMPILE_MAIN
    "<CMAKE_POPCPP_COMPILER>  <FLAGS> -o <OBJECT> <SOURCE>")
   SET(CMAKE_POPCPP_LINK_EXECUTABLE "echo")
ENDIF(NOT CMAKE_POPCPP_COMPILE_OBJECT)
