IF(CMAKE_USER_MAKE_RULES_OVERRIDE)
   INCLUDE(${CMAKE_USER_MAKE_RULE_OVERRIDE})
ENDIF(CMAKE_USER_MAKE_RULES_OVERRIDE)

IF(CMAKE_USER_MAKE_RULES_OVERRIDE_CXX)
   INCLUDE(${CMAKE_USER_MAKE_RULE_OVERRIDE_CXX})
ENDIF(CMAKE_USER_MAKE_RULES_OVERRIDE_CXX)


# Define how cmake must compile a POP-C++ object
IF(NOT CMAKE_POPCPP_COMPILE_OBJECT)
   SET(CMAKE_POPCPP_COMPILE_OBJECT "")
   SET(CMAKE_POPCPP_COMPILE_MAIN "")
   SET(CMAKE_POPCPP_LINK_EXECUTABLE "")
ENDIF(NOT CMAKE_POPCPP_COMPILE_OBJECT)

MACRO(ADD_PARALLEL_OBJECT)
   EXECUTE_PROCESS(COMMAND ${CMAKE_POPCPP_COMPILER} ${POPCPP_FLAGS} ${ARGV})
ENDMACRO(ADD_PARALLEL_OBJECT)

MACRO(ADD_POPCPP_MAIN)
   EXECUTE_PROCESS(COMMAND ${CMAKE_POPCPP_COMPILER} -o ${ARGV})
ENDMACRO(ADD_POPCPP_MAIN)

MACRO(OBJECT_MAP)
   EXECUTE_PROCESS(COMMAND ./${ARG1} -listlong > ${ARG2})
ENDMACRO(OBJECT_MAP)
