
IF(NOT CMAKE_POPCPP_COMPILE_OBJECT)
   SET(CMAKE_CXX_COMPILE_OBJECT
    "<CMAKE_POPCPP_COMPILER>  <FLAGS> -object -o <OBJECT> <SOURCE>")
   SET(CMAKE_POPCPP_COMPILE_MAIN
    "<CMAKE_POPCPP_COMPILER>  <FLAGS> -o <OBJECT> <SOURCE>")
ENDIF(NOT CMAKE_POPCPP_COMPILE_OBJECT)
