include(CMakeForceCompiler)

set(CMAKE_SYSTEM_NAME KComputer)

cmake_force_c_compiler(fccpx GNU)
cmake_force_cxx_compiler(FCCpx GNU)
set(CMAKE_FIND_ROOT_PATH /opt/FJSVtclang/GM-1.2.0-09)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_CXX_OUTPUT_EXTENSION ".o")
set(CMAKE_C_OUTPUT_EXTENSION ".o")
set(CMAKE_CXX_FLAGS "-Xg")
MESSAGE(STATUS "COMPILER COMMAND - ${CMAKE_CXX_COMPILE_OBJECT}")
set(CMAKE_CXX_COMPILE_OBJECT "<CMAKE_CXX_COMPILER> ${CMAKE_CXX_FLAGS} <FLAGS> -o <OBJECT>  -c  <SOURCE>")

set(MPI_COMPILER mpiFCCpx)
set(MPI_COMPILER_FLAGS -o)
